// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// computeDistances
NumericMatrix computeDistances(NumericMatrix genos);
RcppExport SEXP _grcMalaria_computeDistances(SEXP genosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type genos(genosSEXP);
    rcpp_result_gen = Rcpp::wrap(computeDistances(genos));
    return rcpp_result_gen;
END_RCPP
}
// extractBarcodeAlleles
StringMatrix extractBarcodeAlleles(StringVector barcodes, StringVector snpNames);
RcppExport SEXP _grcMalaria_extractBarcodeAlleles(SEXP barcodesSEXP, SEXP snpNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< StringVector >::type snpNames(snpNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(extractBarcodeAlleles(barcodes, snpNames));
    return rcpp_result_gen;
END_RCPP
}
// imputeBarcodesCpp
StringMatrix imputeBarcodesCpp(DataFrame barcodeData, DataFrame barcodeMeta, DataFrame distData);
RcppExport SEXP _grcMalaria_imputeBarcodesCpp(SEXP barcodeDataSEXP, SEXP barcodeMetaSEXP, SEXP distDataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type barcodeData(barcodeDataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type barcodeMeta(barcodeMetaSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type distData(distDataSEXP);
    rcpp_result_gen = Rcpp::wrap(imputeBarcodesCpp(barcodeData, barcodeMeta, distData));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grcMalaria_computeDistances", (DL_FUNC) &_grcMalaria_computeDistances, 1},
    {"_grcMalaria_extractBarcodeAlleles", (DL_FUNC) &_grcMalaria_extractBarcodeAlleles, 2},
    {"_grcMalaria_imputeBarcodesCpp", (DL_FUNC) &_grcMalaria_imputeBarcodesCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_grcMalaria(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
