# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getColumnAlleles <- function(cIdx, colGenotypes) {
    .Call(`_grcMalaria_getColumnAlleles`, cIdx, colGenotypes)
}

getAllelePropTable <- function(colGenotypes, colAlleles) {
    .Call(`_grcMalaria_getAllelePropTable`, colGenotypes, colAlleles)
}

getHomAlleleIndexes <- function(colGenotypes, colAlleles) {
    .Call(`_grcMalaria_getHomAlleleIndexes`, colGenotypes, colAlleles)
}

dist_calculateDistanceMatrix <- function(genotypeData) {
    .Call(`_grcMalaria_dist_calculateDistanceMatrix`, genotypeData)
}

geno_splitString <- function(input, delimiter) {
    .Call(`_grcMalaria_geno_splitString`, input, delimiter)
}

geno_containsChar <- function(input, sub) {
    .Call(`_grcMalaria_geno_containsChar`, input, sub)
}

geno_isMissingGenotype <- function(genoStr) {
    .Call(`_grcMalaria_geno_isMissingGenotype`, genoStr)
}

geno_parseAllele <- function(alleleStr) {
    .Call(`_grcMalaria_geno_parseAllele`, alleleStr)
}

geno_parseGenotypeString <- function(genotypeStr) {
    .Call(`_grcMalaria_geno_parseGenotypeString`, genotypeStr)
}

geno_parseColumnGenotypes <- function(genoStrs, samples) {
    .Call(`_grcMalaria_geno_parseColumnGenotypes`, genoStrs, samples)
}

geno_estimateSampleProperties <- function(samples, genoCols, columnGenoData) {
    .Call(`_grcMalaria_geno_estimateSampleProperties`, samples, genoCols, columnGenoData)
}

geno_estimateColumnProperties <- function(genoCols, columnGenoData) {
    .Call(`_grcMalaria_geno_estimateColumnProperties`, genoCols, columnGenoData)
}

geno_processGenotypes <- function(grcData, genoCols) {
    .Call(`_grcMalaria_geno_processGenotypes`, grcData, genoCols)
}

