# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeDistances <- function(genos) {
    .Call('_grcMalaria_computeDistances', PACKAGE = 'grcMalaria', genos)
}

extractBarcodeAlleles <- function(barcodes, snpNames) {
    .Call('_grcMalaria_extractBarcodeAlleles', PACKAGE = 'grcMalaria', barcodes, snpNames)
}

